(()=>{(function(n){var t=function(G,S){var U=S.cmdlineEl||null,y=S.onModeChange||function(){},H=S.onCommand||function(){},k=S.onCursorMove||function(){},C=S.onHint||function(){},B=null,T=-1,L=["hint: appuyez sur i pour écrire","toujours bloqué ? essayez i ou cliquez sur le texte","vous aussi vous ne savez pas quitter vim ?","on ne vous jugera pas — cliquez sur le texte",":help → just kidding, appuyez sur i"],e=[5000,6000,7000,8000,1e4];function h(){if(B)clearTimeout(B);var j=T+1;if(j>=L.length)return;var q=e[j]||8000;B=setTimeout(function(){if(_==="NORMAL")T=j,C(L[T],T),h()},q)}function u(){if(T=-1,B)clearTimeout(B),B=null;C("",-1)}var _="INSERT",F=null,Y=null,V="",I=[],M=[],jj=/[\p{L}\p{N}_]/u;function R(j){return jj.test(j)}function O(){return G.value}function X(){return G.selectionStart}function Q(j){if(j=Math.max(0,Math.min(j,O().length)),_==="NORMAL"&&j<O().length)G.setSelectionRange(j,j+1);else G.setSelectionRange(j,j);qj(j),k()}function qj(j){var q=O().substring(0,j),z=q.split(`
`).length-1,J=typeof getComputedStyle<"u"?getComputedStyle(G):null,$=J?parseFloat(J.lineHeight):26;if(isNaN($))$=parseFloat(J.fontSize)*1.6||26;var b=z*$,f=b+$;if(b<G.scrollTop)G.scrollTop=b;else if(f>G.scrollTop+G.clientHeight)G.scrollTop=f-G.clientHeight}function zj(j,q){var z=Math.min(j,q),J=Math.max(j,q);G.setSelectionRange(z,J),k()}function W(){return O().split(`
`)}function D(){var j=O().substring(0,X()),q=j.split(`
`);return{line:q.length-1,col:q[q.length-1].length}}function N(j){var q=W();if(j<0||j>=q.length)return null;var z=0;for(var J=0;J<j;J++)z+=q[J].length+1;return{start:z,end:z+q[j].length}}function E(j,q){var z=W();j=Math.max(0,Math.min(j,z.length-1)),q=Math.max(0,Math.min(q,z[j].length));var J=0;for(var $=0;$<j;$++)J+=z[$].length+1;return J+q}function K(){I.push({value:O(),pos:X()}),M=[]}function Gj(){if(I.length===0)return;M.push({value:O(),pos:X()});var j=I.pop();G.value=j.value,Q(j.pos),A()}function Jj(){if(M.length===0)return;I.push({value:O(),pos:X()});var j=M.pop();G.value=j.value,Q(j.pos),A()}function A(){G.dispatchEvent(new Event("input"))}function Z(j){if(_==="INSERT"&&j==="NORMAL")K(),h();if(j!=="NORMAL")u();if(_=j,F=null,Y)clearTimeout(Y),Y=null;if(G.classList.remove("vim-normal","vim-visual"),_==="NORMAL"){G.classList.add("vim-normal");var q=X();if(q<O().length)G.setSelectionRange(q,q+1)}else if(_==="VISUAL")G.classList.add("vim-visual");y(_)}function c(j){var q=D(),z=N(q.line),J=X()+j;if(J<z.start)J=z.start;if(J>z.end)J=z.end;return J}function g(j){var q=D(),z=q.line+j,J=W();if(z<0||z>=J.length)return X();return E(z,q.col)}function v(){var j=O(),q=X();if(q<j.length&&R(j[q]))while(q<j.length&&R(j[q]))q++;while(q<j.length&&!R(j[q])&&j[q]!==`
`)q++;if(q<j.length&&j[q]===`
`)q++;while(q<j.length&&/[ \t]/.test(j[q]))q++;return q}function m(){var j=O(),q=X();if(q===0)return 0;q--;while(q>0&&!R(j[q]))q--;while(q>0&&R(j[q-1]))q--;return q}function x(){var j=O(),q=X();if(q>=j.length-1)return j.length;q++;while(q<j.length&&!R(j[q]))q++;while(q<j.length&&R(j[q]))q++;return Math.max(0,q-1)}function Oj(){var j=D(),q=N(j.line);return q?q.start:X()}function p(){var j=D(),q=N(j.line);return q?q.end:X()}function Qj(){var j=D(),q=W();if(q.length===0)return;if(K(),V=q[j.line]+`
`,q.splice(j.line,1),q.length===0)q=[""];G.value=q.join(`
`);var z=Math.min(j.line,q.length-1);Q(E(z,0)),A()}function Uj(){var j=D(),q=W();V=q[j.line]+`
`}function Xj(){if(!V)return;K();var j=D(),q=N(j.line),z=q.end,J=O(),$=`
`+V.replace(/\n$/,"");G.value=J.substring(0,z)+$+J.substring(z),Q(z+1),A()}function Zj(){var j=X(),q=O();if(j>=q.length)return;K(),G.value=q.substring(0,j)+q.substring(j+1),Q(Math.min(j,O().length)),A()}function _j(){K();var j=D(),q=N(j.line),z=O();G.value=z.substring(0,q.end)+`
`+z.substring(q.end),Q(q.end+1),A(),Z("INSERT")}function $j(){K();var j=D(),q=N(j.line),z=O();G.value=z.substring(0,q.start)+`
`+z.substring(q.start),Q(q.start),A(),Z("INSERT")}var w=0;function Yj(j){j=Math.max(0,Math.min(j,O().length)),zj(w,j)}function Dj(){var{selectionStart:j,selectionEnd:q}=G;if(j===q)return;K(),V=O().substring(j,q),G.value=O().substring(0,j)+O().substring(q),Q(j),A(),Z("NORMAL")}function Nj(){var{selectionStart:j,selectionEnd:q}=G;if(j===q)return;V=O().substring(j,q),Q(j),Z("NORMAL")}function Aj(){if(Z("COMMAND"),U)U.classList.add("active"),U.value=":",U.focus(),U.setSelectionRange(1,1)}function d(){if(U)U.classList.remove("active"),U.value="";G.focus(),Z("NORMAL")}function Fj(){if(!U)return;var j=U.value.replace(/^:/,"").trim();if(U)U.classList.remove("active"),U.value="";if(G.focus(),Z("NORMAL"),j==="wq"||j==="wq!")H("send");else if(j==="q!"||j==="q")H("close")}function Vj(j){if(j.isComposing)return;if(j.key==="Escape"){j.preventDefault();var q=X();Z("NORMAL");var z=D();if(z.col>0)Q(q-1);return}if(j.key==="Enter"&&(j.ctrlKey||j.metaKey)){j.preventDefault(),H("send");return}}function Rj(j){if(j.isComposing)return;var q=j.key;if(q==="Shift"||q==="Control"||q==="Alt"||q==="Meta")return;if(j.preventDefault(),j.key==="Enter"&&(j.ctrlKey||j.metaKey)){H("send");return}if(F){var z=F;if(F=null,Y)clearTimeout(Y),Y=null;if(z==="g"&&q==="g"){Q(0);return}if(z==="d"&&q==="d"){Qj();return}if(z==="y"&&q==="y"){Uj();return}return}if(q==="g"||q==="d"||q==="y"){F=q,Y=setTimeout(function(){F=null},500);return}switch(q){case"h":Q(c(-1));break;case"l":Q(c(1));break;case"j":Q(g(1));break;case"k":Q(g(-1));break;case"w":Q(v());break;case"b":Q(m());break;case"e":Q(x());break;case"0":Q(Oj());break;case"$":Q(p());break;case"G":Q(O().length);break;case"i":Z("INSERT");break;case"a":if(X()<O().length)Q(X()+1);Z("INSERT");break;case"A":Q(p()),Z("INSERT");break;case"o":_j();break;case"O":$j();break;case"p":Xj();break;case"x":Zj();break;case"u":Gj();break;case"r":if(j.ctrlKey)Jj();break;case"v":Kj();break;case":":Aj();break}}function Kj(){w=X(),Z("VISUAL")}function bj(j){if(j.isComposing)return;var q=j.key;if(q==="Shift"||q==="Control"||q==="Alt"||q==="Meta")return;if(j.preventDefault(),j.key==="Enter"&&(j.ctrlKey||j.metaKey)){H("send");return}if(q==="Escape"){Q(X()),Z("NORMAL");return}var z=G.selectionEnd===w?G.selectionStart:G.selectionEnd,J=z;switch(q){case"h":J=Math.max(0,z-1);break;case"l":J=Math.min(O().length,z+1);break;case"j":{var $=O().substring(0,z),b=$.split(`
`),f=b.length-1,Bj=b[b.length-1].length,Wj=W();if(f<Wj.length-1)J=E(f+1,Bj);break}case"k":{var Sj=O().substring(0,z),P=Sj.split(`
`),r=P.length-1,Hj=P[P.length-1].length;if(r>0)J=E(r-1,Hj);break}case"w":J=v();break;case"b":J=m();break;case"e":J=x();break;case"0":{var Tj=O().substring(0,z),Ij=Tj.split(`
`),Mj=Ij.length-1,o=N(Mj);J=o?o.start:z;break}case"$":{var fj=O().substring(0,z),Ej=fj.split(`
`),wj=Ej.length-1,a=N(wj);J=a?a.end:z;break}case"G":J=O().length;break;case"d":Dj();return;case"y":Nj();return}Yj(J)}function l(j){switch(_){case"INSERT":Vj(j);break;case"NORMAL":Rj(j);break;case"VISUAL":bj(j);break}}function s(j){if(j.key==="Escape"){j.preventDefault(),j.stopPropagation(),d();return}if(j.key==="Enter"){j.preventDefault(),j.stopPropagation(),Fj();return}if(j.key==="Backspace"&&U.value===":"){j.preventDefault(),d();return}}function i(){if(_==="NORMAL"||_==="VISUAL")Z("INSERT")}if(G.addEventListener("keydown",l),G.addEventListener("click",i),U)U.addEventListener("keydown",s);return{destroy:function(){if(G.removeEventListener("keydown",l),G.removeEventListener("click",i),U)U.removeEventListener("keydown",s)},reset:function(){if(_="INSERT",F=null,Y)clearTimeout(Y),Y=null;V="",I=[],M=[],u(),G.classList.remove("vim-normal","vim-visual"),y("INSERT")},getMode:function(){return _}}};n.VimEngine=t})(typeof window<"u"?window:globalThis);})();
