(()=>{(function(a){var n=function(J,B){var U=B.cmdlineEl||null,P=B.onModeChange||function(){},S=B.onCommand||function(){},y=B.onCursorMove||function(){},k=B.onHint||function(){},K=null,H=-1,C=["hint: appuyez sur i pour écrire","toujours bloqué ? essayez i ou cliquez sur le texte","vous aussi vous ne savez pas quitter vim ?","on ne vous jugera pas — cliquez sur le texte",":help → just kidding, appuyez sur i"],t=[5000,6000,7000,8000,1e4];function h(){if(K)clearTimeout(K);var j=H+1;if(j>=C.length)return;var q=t[j]||8000;K=setTimeout(function(){if(_==="NORMAL")H=j,k(C[H],H),h()},q)}function L(){if(H=-1,K)clearTimeout(K),K=null;k("",-1)}var _="INSERT",F=null,Y=null,V="",T=[],I=[];function O(){return J.value}function X(){return J.selectionStart}function Q(j){if(j=Math.max(0,Math.min(j,O().length)),_==="NORMAL"&&j<O().length)J.setSelectionRange(j,j+1);else J.setSelectionRange(j,j);e(j),y()}function e(j){var q=O().substring(0,j),z=q.split(`
`).length-1,G=typeof getComputedStyle<"u"?getComputedStyle(J):null,$=G?parseFloat(G.lineHeight):26;if(isNaN($))$=parseFloat(G.fontSize)*1.6||26;var R=z*$,M=R+$;if(R<J.scrollTop)J.scrollTop=R;else if(M>J.scrollTop+J.clientHeight)J.scrollTop=M-J.clientHeight}function jj(j,q){var z=Math.min(j,q),G=Math.max(j,q);J.setSelectionRange(z,G),y()}function b(){return O().split(`
`)}function D(){var j=O().substring(0,X()),q=j.split(`
`);return{line:q.length-1,col:q[q.length-1].length}}function N(j){var q=b();if(j<0||j>=q.length)return null;var z=0;for(var G=0;G<j;G++)z+=q[G].length+1;return{start:z,end:z+q[j].length}}function f(j,q){var z=b();j=Math.max(0,Math.min(j,z.length-1)),q=Math.max(0,Math.min(q,z[j].length));var G=0;for(var $=0;$<j;$++)G+=z[$].length+1;return G+q}function W(){T.push({value:O(),pos:X()}),I=[]}function qj(){if(T.length===0)return;I.push({value:O(),pos:X()});var j=T.pop();J.value=j.value,Q(j.pos),A()}function zj(){if(I.length===0)return;T.push({value:O(),pos:X()});var j=I.pop();J.value=j.value,Q(j.pos),A()}function A(){J.dispatchEvent(new Event("input"))}function Z(j){if(_==="INSERT"&&j==="NORMAL")W(),h();if(j!=="NORMAL")L();if(_=j,F=null,Y)clearTimeout(Y),Y=null;if(J.classList.remove("vim-normal","vim-visual"),_==="NORMAL"){J.classList.add("vim-normal");var q=X();if(q<O().length)J.setSelectionRange(q,q+1)}else if(_==="VISUAL")J.classList.add("vim-visual");P(_)}function u(j){var q=D(),z=N(q.line),G=X()+j;if(G<z.start)G=z.start;if(G>z.end)G=z.end;return G}function c(j){var q=D(),z=q.line+j,G=b();if(z<0||z>=G.length)return X();return f(z,q.col)}function v(){var j=O(),q=X(),z=/\w/;if(q<j.length&&z.test(j[q]))while(q<j.length&&z.test(j[q]))q++;while(q<j.length&&!z.test(j[q])&&j[q]!==`
`)q++;if(q<j.length&&j[q]===`
`)q++;while(q<j.length&&/[ \t]/.test(j[q]))q++;return q}function m(){var j=O(),q=X();if(q===0)return 0;q--;while(q>0&&!/\w/.test(j[q]))q--;while(q>0&&/\w/.test(j[q-1]))q--;return q}function x(){var j=O(),q=X();if(q>=j.length-1)return j.length;q++;while(q<j.length&&!/\w/.test(j[q]))q++;while(q<j.length&&/\w/.test(j[q]))q++;return Math.max(0,q-1)}function Gj(){var j=D(),q=N(j.line);return q?q.start:X()}function g(){var j=D(),q=N(j.line);return q?q.end:X()}function Jj(){var j=D(),q=b();if(q.length===0)return;if(W(),V=q[j.line]+`
`,q.splice(j.line,1),q.length===0)q=[""];J.value=q.join(`
`);var z=Math.min(j.line,q.length-1);Q(f(z,0)),A()}function Oj(){var j=D(),q=b();V=q[j.line]+`
`}function Qj(){if(!V)return;W();var j=D(),q=N(j.line),z=q.end,G=O(),$=`
`+V.replace(/\n$/,"");J.value=G.substring(0,z)+$+G.substring(z),Q(z+1),A()}function Uj(){var j=X(),q=O();if(j>=q.length)return;W(),J.value=q.substring(0,j)+q.substring(j+1),Q(Math.min(j,O().length)),A()}function Xj(){W();var j=D(),q=N(j.line),z=O();J.value=z.substring(0,q.end)+`
`+z.substring(q.end),Q(q.end+1),A(),Z("INSERT")}function Zj(){W();var j=D(),q=N(j.line),z=O();J.value=z.substring(0,q.start)+`
`+z.substring(q.start),Q(q.start),A(),Z("INSERT")}var E=0;function _j(j){j=Math.max(0,Math.min(j,O().length)),jj(E,j)}function $j(){var{selectionStart:j,selectionEnd:q}=J;if(j===q)return;W(),V=O().substring(j,q),J.value=O().substring(0,j)+O().substring(q),Q(j),A(),Z("NORMAL")}function Yj(){var{selectionStart:j,selectionEnd:q}=J;if(j===q)return;V=O().substring(j,q),Q(j),Z("NORMAL")}function Dj(){if(Z("COMMAND"),U)U.classList.add("active"),U.value=":",U.focus(),U.setSelectionRange(1,1)}function p(){if(U)U.classList.remove("active"),U.value="";J.focus(),Z("NORMAL")}function Nj(){if(!U)return;var j=U.value.replace(/^:/,"").trim();if(U)U.classList.remove("active"),U.value="";if(J.focus(),Z("NORMAL"),j==="wq"||j==="wq!")S("send");else if(j==="q!"||j==="q")S("close")}function Aj(j){if(j.isComposing)return;if(j.key==="Escape"){j.preventDefault();var q=X();if(Z("NORMAL"),q>0){var z=D(),G=N(z.line);if(G&&q>G.end)Q(G.end>G.start?G.end-1:G.start)}return}if(j.key==="Enter"&&(j.ctrlKey||j.metaKey)){j.preventDefault(),S("send");return}}function Fj(j){if(j.isComposing)return;var q=j.key;if(q==="Shift"||q==="Control"||q==="Alt"||q==="Meta")return;if(j.preventDefault(),j.key==="Enter"&&(j.ctrlKey||j.metaKey)){S("send");return}if(F){var z=F;if(F=null,Y)clearTimeout(Y),Y=null;if(z==="g"&&q==="g"){Q(0);return}if(z==="d"&&q==="d"){Jj();return}if(z==="y"&&q==="y"){Oj();return}return}if(q==="g"||q==="d"||q==="y"){F=q,Y=setTimeout(function(){F=null},500);return}switch(q){case"h":Q(u(-1));break;case"l":Q(u(1));break;case"j":Q(c(1));break;case"k":Q(c(-1));break;case"w":Q(v());break;case"b":Q(m());break;case"e":Q(x());break;case"0":Q(Gj());break;case"$":Q(g());break;case"G":Q(O().length);break;case"i":Z("INSERT");break;case"a":if(X()<O().length)Q(X()+1);Z("INSERT");break;case"A":Q(g()),Z("INSERT");break;case"o":Xj();break;case"O":Zj();break;case"p":Qj();break;case"x":Uj();break;case"u":qj();break;case"r":if(j.ctrlKey)zj();break;case"v":Vj();break;case":":Dj();break}}function Vj(){E=X(),Z("VISUAL")}function Wj(j){if(j.isComposing)return;var q=j.key;if(q==="Shift"||q==="Control"||q==="Alt"||q==="Meta")return;if(j.preventDefault(),j.key==="Enter"&&(j.ctrlKey||j.metaKey)){S("send");return}if(q==="Escape"){Q(X()),Z("NORMAL");return}var z=J.selectionEnd===E?J.selectionStart:J.selectionEnd,G=z;switch(q){case"h":G=Math.max(0,z-1);break;case"l":G=Math.min(O().length,z+1);break;case"j":var $=O().substring(0,z),R=$.split(`
`),M=R.length-1,Rj=R[R.length-1].length,Kj=b();if(M<Kj.length-1)G=f(M+1,Rj);break;case"k":var bj=O().substring(0,z),w=bj.split(`
`),i=w.length-1,Bj=w[w.length-1].length;if(i>0)G=f(i-1,Bj);break;case"w":G=v();break;case"b":G=m();break;case"e":G=x();break;case"0":var Sj=O().substring(0,z),Hj=Sj.split(`
`),Tj=Hj.length-1,r=N(Tj);G=r?r.start:z;break;case"$":var Ij=O().substring(0,z),Mj=Ij.split(`
`),fj=Mj.length-1,o=N(fj);G=o?o.end:z;break;case"G":G=O().length;break;case"d":$j();return;case"y":Yj();return}_j(G)}function d(j){switch(_){case"INSERT":Aj(j);break;case"NORMAL":Fj(j);break;case"VISUAL":Wj(j);break}}function l(j){if(j.key==="Escape"){j.preventDefault(),j.stopPropagation(),p();return}if(j.key==="Enter"){j.preventDefault(),j.stopPropagation(),Nj();return}if(j.key==="Backspace"&&U.value===":"){j.preventDefault(),p();return}}function s(){if(_==="NORMAL"||_==="VISUAL")Z("INSERT")}if(J.addEventListener("keydown",d),J.addEventListener("click",s),U)U.addEventListener("keydown",l);return{destroy:function(){if(J.removeEventListener("keydown",d),J.removeEventListener("click",s),U)U.removeEventListener("keydown",l)},reset:function(){if(_="INSERT",F=null,Y)clearTimeout(Y),Y=null;V="",T=[],I=[],L(),J.classList.remove("vim-normal","vim-visual"),P("INSERT")},getMode:function(){return _}}};a.VimEngine=n})(typeof window<"u"?window:globalThis);})();
