(()=>{var Pj=(w,F)=>()=>(F||w((F={exports:{}}).exports,F),F.exports);var wj=Pj((kj,P)=>{(function(w){var F=function(J,S){var X=S.cmdlineEl||null,C=S.onModeChange||function(){},T=S.onCommand||function(){},h=S.onCursorMove||function(){},L=S.onHint||function(){},b=null,H=-1,u=["hint: appuyez sur i pour écrire","toujours bloqué ? essayez i ou cliquez sur le texte","vous aussi vous ne savez pas quitter vim ?","on ne vous jugera pas — cliquez sur le texte",":help → just kidding, appuyez sur i"],e=[5000,6000,7000,8000,1e4];function c(){if(b)clearTimeout(b);var j=H+1;if(j>=u.length)return;var q=e[j]||8000;b=setTimeout(function(){if($==="NORMAL")H=j,L(u[H],H),c()},q)}function v(){if(H=-1,b)clearTimeout(b),b=null;L("",-1)}var $="INSERT",V=null,Y=null,W="",I=[],M=[];function O(){return J.value}function Z(){return J.selectionStart}function Q(j){if(j=Math.max(0,Math.min(j,O().length)),$==="NORMAL"&&j<O().length)J.setSelectionRange(j,j+1);else J.setSelectionRange(j,j);jj(j),h()}function jj(j){var q=O().substring(0,j),z=q.split(`
`).length-1,G=typeof getComputedStyle<"u"?getComputedStyle(J):null,U=G?parseFloat(G.lineHeight):26;if(isNaN(U))U=parseFloat(G.fontSize)*1.6||26;var K=z*U,f=K+U;if(K<J.scrollTop)J.scrollTop=K;else if(f>J.scrollTop+J.clientHeight)J.scrollTop=f-J.clientHeight}function qj(j,q){var z=Math.min(j,q),G=Math.max(j,q);J.setSelectionRange(z,G),h()}function B(){return O().split(`
`)}function D(){var j=O().substring(0,Z()),q=j.split(`
`);return{line:q.length-1,col:q[q.length-1].length}}function A(j){var q=B();if(j<0||j>=q.length)return null;var z=0;for(var G=0;G<j;G++)z+=q[G].length+1;return{start:z,end:z+q[j].length}}function E(j,q){var z=B();j=Math.max(0,Math.min(j,z.length-1)),q=Math.max(0,Math.min(q,z[j].length));var G=0;for(var U=0;U<j;U++)G+=z[U].length+1;return G+q}function R(){I.push({value:O(),pos:Z()}),M=[]}function zj(){if(I.length===0)return;M.push({value:O(),pos:Z()});var j=I.pop();J.value=j.value,Q(j.pos),N()}function Gj(){if(M.length===0)return;I.push({value:O(),pos:Z()});var j=M.pop();J.value=j.value,Q(j.pos),N()}function N(){J.dispatchEvent(new Event("input"))}function _(j){if($==="INSERT"&&j==="NORMAL")R(),c();if(j!=="NORMAL")v();if($=j,V=null,Y)clearTimeout(Y),Y=null;if(J.classList.remove("vim-normal","vim-visual"),$==="NORMAL"){J.classList.add("vim-normal");var q=Z();if(q<O().length)J.setSelectionRange(q,q+1)}else if($==="VISUAL")J.classList.add("vim-visual");C($)}function m(j){var q=D(),z=A(q.line),G=Z()+j;if(G<z.start)G=z.start;if(G>z.end)G=z.end;return G}function x(j){var q=D(),z=q.line+j,G=B();if(z<0||z>=G.length)return Z();return E(z,q.col)}function g(){var j=O(),q=Z(),z=/\w/;if(q<j.length&&z.test(j[q]))while(q<j.length&&z.test(j[q]))q++;while(q<j.length&&!z.test(j[q])&&j[q]!==`
`)q++;if(q<j.length&&j[q]===`
`)q++;while(q<j.length&&/[ \t]/.test(j[q]))q++;return q}function p(){var j=O(),q=Z();if(q===0)return 0;q--;while(q>0&&!/\w/.test(j[q]))q--;while(q>0&&/\w/.test(j[q-1]))q--;return q}function d(){var j=O(),q=Z();if(q>=j.length-1)return j.length;q++;while(q<j.length&&!/\w/.test(j[q]))q++;while(q<j.length&&/\w/.test(j[q]))q++;return Math.max(0,q-1)}function Jj(){var j=D(),q=A(j.line);return q?q.start:Z()}function l(){var j=D(),q=A(j.line);return q?q.end:Z()}function Oj(){var j=D(),q=B();if(q.length===0)return;if(R(),W=q[j.line]+`
`,q.splice(j.line,1),q.length===0)q=[""];J.value=q.join(`
`);var z=Math.min(j.line,q.length-1);Q(E(z,0)),N()}function Qj(){var j=D(),q=B();W=q[j.line]+`
`}function Xj(){if(!W)return;R();var j=D(),q=A(j.line),z=q.end,G=O(),U=`
`+W.replace(/\n$/,"");J.value=G.substring(0,z)+U+G.substring(z),Q(z+1),N()}function Zj(){var j=Z(),q=O();if(j>=q.length)return;R(),J.value=q.substring(0,j)+q.substring(j+1),Q(Math.min(j,O().length)),N()}function _j(){R();var j=D(),q=A(j.line),z=O();J.value=z.substring(0,q.end)+`
`+z.substring(q.end),Q(q.end+1),N(),_("INSERT")}function $j(){R();var j=D(),q=A(j.line),z=O();J.value=z.substring(0,q.start)+`
`+z.substring(q.start),Q(q.start),N(),_("INSERT")}var y=0;function Uj(j){j=Math.max(0,Math.min(j,O().length)),qj(y,j)}function Yj(){var{selectionStart:j,selectionEnd:q}=J;if(j===q)return;R(),W=O().substring(j,q),J.value=O().substring(0,j)+O().substring(q),Q(j),N(),_("NORMAL")}function Dj(){var{selectionStart:j,selectionEnd:q}=J;if(j===q)return;W=O().substring(j,q),Q(j),_("NORMAL")}function Aj(){if(_("COMMAND"),X)X.classList.add("active"),X.value=":",X.focus(),X.setSelectionRange(1,1)}function s(){if(X)X.classList.remove("active"),X.value="";J.focus(),_("NORMAL")}function Nj(){if(!X)return;var j=X.value.replace(/^:/,"").trim();if(X)X.classList.remove("active"),X.value="";if(J.focus(),_("NORMAL"),j==="wq"||j==="wq!")T("send");else if(j==="q!"||j==="q")T("close")}function Fj(j){if(j.isComposing)return;if(j.key==="Escape"){j.preventDefault();var q=Z();if(_("NORMAL"),q>0){var z=D(),G=A(z.line);if(G&&q>G.end)Q(G.end>G.start?G.end-1:G.start)}return}if(j.key==="Enter"&&(j.ctrlKey||j.metaKey)){j.preventDefault(),T("send");return}}function Vj(j){if(j.isComposing)return;var q=j.key;if(q==="Shift"||q==="Control"||q==="Alt"||q==="Meta")return;if(j.preventDefault(),j.key==="Enter"&&(j.ctrlKey||j.metaKey)){T("send");return}if(V){var z=V;if(V=null,Y)clearTimeout(Y),Y=null;if(z==="g"&&q==="g"){Q(0);return}if(z==="d"&&q==="d"){Oj();return}if(z==="y"&&q==="y"){Qj();return}return}if(q==="g"||q==="d"||q==="y"){V=q,Y=setTimeout(function(){V=null},500);return}switch(q){case"h":Q(m(-1));break;case"l":Q(m(1));break;case"j":Q(x(1));break;case"k":Q(x(-1));break;case"w":Q(g());break;case"b":Q(p());break;case"e":Q(d());break;case"0":Q(Jj());break;case"$":Q(l());break;case"G":Q(O().length);break;case"i":_("INSERT");break;case"a":if(Z()<O().length)Q(Z()+1);_("INSERT");break;case"A":Q(l()),_("INSERT");break;case"o":_j();break;case"O":$j();break;case"p":Xj();break;case"x":Zj();break;case"u":zj();break;case"r":if(j.ctrlKey)Gj();break;case"v":Wj();break;case":":Aj();break}}function Wj(){y=Z(),_("VISUAL")}function Rj(j){if(j.isComposing)return;var q=j.key;if(q==="Shift"||q==="Control"||q==="Alt"||q==="Meta")return;if(j.preventDefault(),j.key==="Enter"&&(j.ctrlKey||j.metaKey)){T("send");return}if(q==="Escape"){Q(Z()),_("NORMAL");return}var z=J.selectionEnd===y?J.selectionStart:J.selectionEnd,G=z;switch(q){case"h":G=Math.max(0,z-1);break;case"l":G=Math.min(O().length,z+1);break;case"j":var U=O().substring(0,z),K=U.split(`
`),f=K.length-1,Kj=K[K.length-1].length,bj=B();if(f<bj.length-1)G=E(f+1,Kj);break;case"k":var Bj=O().substring(0,z),k=Bj.split(`
`),a=k.length-1,Sj=k[k.length-1].length;if(a>0)G=E(a-1,Sj);break;case"w":G=g();break;case"b":G=p();break;case"e":G=d();break;case"0":var Tj=O().substring(0,z),Hj=Tj.split(`
`),Ij=Hj.length-1,n=A(Ij);G=n?n.start:z;break;case"$":var Mj=O().substring(0,z),fj=Mj.split(`
`),Ej=fj.length-1,t=A(Ej);G=t?t.end:z;break;case"G":G=O().length;break;case"d":Yj();return;case"y":Dj();return}Uj(G)}function i(j){switch($){case"INSERT":Fj(j);break;case"NORMAL":Vj(j);break;case"VISUAL":Rj(j);break}}function r(j){if(j.key==="Escape"){j.preventDefault(),j.stopPropagation(),s();return}if(j.key==="Enter"){j.preventDefault(),j.stopPropagation(),Nj();return}if(j.key==="Backspace"&&X.value===":"){j.preventDefault(),s();return}}function o(){if($==="NORMAL"||$==="VISUAL")_("INSERT")}if(J.addEventListener("keydown",i),J.addEventListener("click",o),X)X.addEventListener("keydown",r);return{destroy:function(){if(J.removeEventListener("keydown",i),J.removeEventListener("click",o),X)X.removeEventListener("keydown",r)},reset:function(){if($="INSERT",V=null,Y)clearTimeout(Y),Y=null;W="",I=[],M=[],v(),J.classList.remove("vim-normal","vim-visual"),C("INSERT")},getMode:function(){return $}}};if(typeof P<"u"&&P.exports)P.exports=F;else w.VimEngine=F})(typeof window<"u"?window:globalThis)});})();
